"""add parametros_coor table

Revision ID: 0098ca72b7aa
Revises: 1179c83fffae
Create Date: 2026-06-22 15:27:32.743816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0098ca72b7aa'
down_revision = '1179c83fffae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametros_coor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parametro', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parametro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recursos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recurso', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tipo_cuadrilla', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('meta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('recursos_pkey')),
    sa.UniqueConstraint('recurso', name=op.f('recursos_recurso_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('parametros_coor')
    # ### end Alembic commands ###
