"""campos_respuesta_coordinador

Revision ID: 08a17aad1274
Revises: c5b09b95be9c
Create Date: 2026-06-11 15:12:22.836424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a17aad1274'
down_revision = 'c5b09b95be9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_operacionales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respuesta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parametro_coordinador', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('evidencia_coor_1', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('evidencia_coor_2', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('estado_conformidad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('accion_a_tomar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('respondido_por', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('fecha_respuesta', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_operacionales', schema=None) as batch_op:
        batch_op.drop_column('fecha_respuesta')
        batch_op.drop_column('respondido_por')
        batch_op.drop_column('accion_a_tomar')
        batch_op.drop_column('estado_conformidad')
        batch_op.drop_column('evidencia_coor_2')
        batch_op.drop_column('evidencia_coor_1')
        batch_op.drop_column('parametro_coordinador')
        batch_op.drop_column('respuesta')

    # ### end Alembic commands ###
