"""add acciones_tomar table

Revision ID: 1179c83fffae
Revises: 883fa01ea191
Create Date: 2026-06-22 15:18:45.750288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1179c83fffae'
down_revision = '883fa01ea191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acciones_tomar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recursos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recurso', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tipo_cuadrilla', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('meta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('recursos_pkey')),
    sa.UniqueConstraint('recurso', name=op.f('recursos_recurso_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('acciones_tomar')
    # ### end Alembic commands ###
