"""activo_contrato

Revision ID: 17410c3005db
Revises: 296622190dc6
Create Date: 2026-06-20 16:00:26.007212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17410c3005db'
down_revision = '296622190dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default='TRUE', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
