"""tabla actividades

Revision ID: 34303400dfce
Revises: b5f9d55733fe
Create Date: 2026-06-02 10:40:01.157496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34303400dfce'
down_revision = 'b5f9d55733fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad', sa.Text(), nullable=False),
    sa.Column('proceso', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actividad')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades')
    # ### end Alembic commands ###
