"""add origen to distribucion_operativa

Revision ID: 62fa5af69161
Revises: 6feadfad3f22
Create Date: 2026-07-11 16:23:08.612400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fa5af69161'
down_revision = '6feadfad3f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribucion_operativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribucion_operativa', schema=None) as batch_op:
        batch_op.drop_column('origen')

    op.create_table('recursos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recurso', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tipo_cuadrilla', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('meta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('recursos_pkey')),
    sa.UniqueConstraint('recurso', name=op.f('recursos_recurso_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
