"""tabla parametros neo

Revision ID: 6b28f3bc5ac1
Revises: 80f89eb547a6
Create Date: 2026-05-29 16:24:10.125264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b28f3bc5ac1'
down_revision = '80f89eb547a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametros_neo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parametroNeo', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parametroNeo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parametros_neo')
    # ### end Alembic commands ###
