"""actividad contrato

Revision ID: 6d7daa8cc763
Revises: 34303400dfce
Create Date: 2026-06-02 10:46:16.433416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7daa8cc763'
down_revision = '34303400dfce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato', sa.String(length=250), nullable=True))
        batch_op.drop_constraint(batch_op.f('actividades_actividad_key'), type_='unique')
        batch_op.drop_column('proceso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proceso', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('actividades_actividad_key'), ['actividad'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('contrato')

    # ### end Alembic commands ###
