"""add notificaciones table

Revision ID: 6feadfad3f22
Revises: 9286dabee60a
Create Date: 2026-06-24 16:42:04.723183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6feadfad3f22'
down_revision = '9286dabee60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_destino', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('reporte_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=300), nullable=False),
    sa.Column('contrato', sa.String(length=200), nullable=True),
    sa.Column('recurso', sa.String(length=200), nullable=True),
    sa.Column('fecha_reporte', sa.String(length=20), nullable=True),
    sa.Column('tipo_incidencia', sa.String(length=200), nullable=True),
    sa.Column('gestionada', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_usuario_destino'), ['usuario_destino'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recursos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recurso', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tipo_cuadrilla', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('meta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('recursos_pkey')),
    sa.UniqueConstraint('recurso', name=op.f('recursos_recurso_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_usuario_destino'))

    op.drop_table('notificaciones')
    # ### end Alembic commands ###
