"""tabla metas operativas

Revision ID: 80f89eb547a6
Revises: 886b8f653d0d
Create Date: 2026-05-29 16:10:59.692644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f89eb547a6'
down_revision = '886b8f653d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metas_operativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Tipo_cuadrilla', sa.String(length=150), nullable=False),
    sa.Column('Proceso', sa.String(length=150), nullable=True),
    sa.Column('Meta_Produccion', sa.Float(), nullable=False),
    sa.Column('Contrato', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metas_operativas')
    # ### end Alembic commands ###
