"""contrato_campos_sede_codigo_proceso

Revision ID: 883fa01ea191
Revises: 17410c3005db
Create Date: 2026-06-20 16:47:43.291056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883fa01ea191'
down_revision = '17410c3005db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sede', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('proceso', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_contratos_codigo'), ['codigo'], unique=True)

    with op.batch_alter_table('distribucion_operativa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sede', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribucion_operativa', schema=None) as batch_op:
        batch_op.drop_column('sede')

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_codigo'))
        batch_op.drop_column('proceso')
        batch_op.drop_column('sede')
        batch_op.drop_column('nombre')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
