"""tabla personas

Revision ID: 886b8f653d0d
Revises: f19370e39122
Create Date: 2026-05-29 16:04:12.037713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886b8f653d0d'
down_revision = 'f19370e39122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Cargo', sa.String(length=150), nullable=False),
    sa.Column('Documento', sa.String(length=50), nullable=False),
    sa.Column('Salario', sa.Float(), nullable=True),
    sa.Column('Nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Documento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personas')
    # ### end Alembic commands ###
