"""add alertas_gps table

Revision ID: 9286dabee60a
Revises: 0098ca72b7aa
Create Date: 2026-06-24 11:16:37.050539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9286dabee60a'
down_revision = '0098ca72b7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas_gps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id_gps', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=80), nullable=True),
    sa.Column('triggered_at', sa.String(length=50), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('metadata_raw', sa.Text(), nullable=True),
    sa.Column('contract_code', sa.String(length=50), nullable=True),
    sa.Column('contract_group', sa.String(length=10), nullable=True),
    sa.Column('resource_code', sa.String(length=50), nullable=True),
    sa.Column('brigade_type', sa.String(length=50), nullable=True),
    sa.Column('plan_date', sa.String(length=20), nullable=True),
    sa.Column('tech1_doc', sa.BigInteger(), nullable=True),
    sa.Column('tech2_doc', sa.BigInteger(), nullable=True),
    sa.Column('tech3_doc', sa.BigInteger(), nullable=True),
    sa.Column('tech4_doc', sa.BigInteger(), nullable=True),
    sa.Column('tech5_doc', sa.BigInteger(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=100), nullable=True),
    sa.Column('item_duration_min', sa.Integer(), nullable=True),
    sa.Column('estado_local', sa.String(length=20), nullable=False),
    sa.Column('atendida_por', sa.String(length=100), nullable=True),
    sa.Column('fecha_atencion', sa.DateTime(), nullable=True),
    sa.Column('fecha_recibida', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id_gps')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recursos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recurso', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tipo_cuadrilla', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('meta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('recursos_pkey')),
    sa.UniqueConstraint('recurso', name=op.f('recursos_recurso_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('alertas_gps')
    # ### end Alembic commands ###
