"""tabla recursos

Revision ID: 9dfafbd9ece8
Revises: fd2c99a98732
Create Date: 2026-05-28 16:52:34.253793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfafbd9ece8'
down_revision = 'fd2c99a98732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribucion_operativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('contrato', sa.String(length=200), nullable=False),
    sa.Column('recurso', sa.String(length=200), nullable=False),
    sa.Column('placa', sa.String(length=50), nullable=True),
    sa.Column('orden_trabajo', sa.String(length=100), nullable=True),
    sa.Column('tipo_actividad', sa.String(length=200), nullable=True),
    sa.Column('tipo_cuadrilla', sa.String(length=200), nullable=True),
    sa.Column('hora_salida_sede', sa.Time(), nullable=True),
    sa.Column('hora_llegada_sede', sa.Time(), nullable=True),
    sa.Column('cedula_1', sa.String(length=50), nullable=True),
    sa.Column('cedula_2', sa.String(length=50), nullable=True),
    sa.Column('cedula_3', sa.String(length=50), nullable=True),
    sa.Column('cedula_4', sa.String(length=50), nullable=True),
    sa.Column('cedula_5', sa.String(length=50), nullable=True),
    sa.Column('numero_celular', sa.String(length=50), nullable=True),
    sa.Column('latitud', sa.String(length=100), nullable=True),
    sa.Column('longitud', sa.String(length=100), nullable=True),
    sa.Column('duracion_actividad', sa.String(length=50), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('meta', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso', sa.String(length=200), nullable=False),
    sa.Column('tipo_cuadrilla', sa.String(length=200), nullable=True),
    sa.Column('meta', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recursos')
    op.drop_table('distribucion_operativa')
    # ### end Alembic commands ###
