"""tabla placa contrato

Revision ID: b5f9d55733fe
Revises: e5ea8dd31a5f
Create Date: 2026-06-02 08:18:40.228868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f9d55733fe'
down_revision = 'e5ea8dd31a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placa_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=50), nullable=False),
    sa.Column('contrato', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placa_contrato')
    # ### end Alembic commands ###
