"""Reporte_Operacional

Revision ID: c5b09b95be9c
Revises: 6d7daa8cc763
Create Date: 2026-06-09 17:06:14.498404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b09b95be9c'
down_revision = '6d7daa8cc763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes_operacionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.Date(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), nullable=True),
    sa.Column('contrato', sa.String(length=250), nullable=False),
    sa.Column('recurso', sa.String(length=150), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('tipo_cuadrilla', sa.String(length=150), nullable=True),
    sa.Column('meta', sa.Float(), nullable=True),
    sa.Column('tipo_actividad', sa.String(length=150), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('tipo_incidencia', sa.String(length=200), nullable=False),
    sa.Column('parametro_neo', sa.String(length=200), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('duracion', sa.String(length=20), nullable=True),
    sa.Column('impacto', sa.String(length=50), nullable=True),
    sa.Column('horas_afectadas', sa.Float(), nullable=True),
    sa.Column('afectacion_economica', sa.Float(), nullable=True),
    sa.Column('evidencia_1', sa.String(length=300), nullable=False),
    sa.Column('evidencia_2', sa.String(length=300), nullable=True),
    sa.Column('reportado_por', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes_operacionales')
    # ### end Alembic commands ###
