"""tabla tipos desvio

Revision ID: cd2c8f65d799
Revises: 6b28f3bc5ac1
Create Date: 2026-05-29 16:35:15.466386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2c8f65d799'
down_revision = '6b28f3bc5ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_desvio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_desvio', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_desvio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipos_desvio')
    # ### end Alembic commands ###
