"""tabla recurso contrato

Revision ID: e5ea8dd31a5f
Revises: 0822b19255a4
Create Date: 2026-06-02 08:08:31.719389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ea8dd31a5f'
down_revision = '0822b19255a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurso_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato', sa.Text(), nullable=False),
    sa.Column('recurso', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurso_contrato')
    # ### end Alembic commands ###
