"""tabla contratos

Revision ID: f19370e39122
Revises: 9dfafbd9ece8
Create Date: 2026-05-29 15:47:56.621243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19370e39122'
down_revision = '9dfafbd9ece8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato', sa.String(length=200), nullable=False),
    sa.Column('coordinador', sa.String(length=150), nullable=True),
    sa.Column('director', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contratos')
    # ### end Alembic commands ###
